"""Cosmobox Level1B: gauge-invariant relational correlators.

Lots 1B-1 (paths, transporters, dressed matter operators and their matrix
assembly) and 1B-2 (local charge/flavor observables and pure-state
correlators). Reuses Level0's validated primitives (lattice, encoding,
operators, hamiltonian.build_key_index/validate_key_index) without
modification, per docs/levels/level1/implementation-design.md section 2.1.
"""

from .automorphisms import (
    GraphAutomorphism,
    UnitaryAutomorphism,
    build_automorphism,
    compose,
    compose_unitary_automorphisms,
    generate_closed_subgroup,
    generate_closed_unitary_subgroup,
    hamiltonian_commutator_defect,
    identity_automorphism,
    identity_unitary_automorphism,
    reflection_automorphism,
    reflection_unitary_automorphism,
    symmetry_subgroup,
    transform_oriented_path,
    translation_automorphism,
    translation_unitary_automorphism,
)
from .diagnostics import (
    HermitianRestrictedDiagnostics,
    NonHermitianRestrictedDiagnostics,
    build_hermitian_restricted_diagnostics,
    build_non_hermitian_restricted_diagnostics,
)
from .flavor import (
    FlavorCorrelatorMatrix,
    build_flavor_correlator_matrix,
    flavor_frobenius_squared,
    flavor_singlet,
    flavor_singular_value_ratio,
    flavor_singular_values,
)
from .local_observables import (
    FLAVOR_COMPONENTS,
    NORMALIZATION_FLOOR,
    NormalizedMoment,
    build_local_charge_operator,
    build_local_flavor_generator,
    build_local_flavor_generators,
    charge_correlator_connected,
    charge_correlator_raw,
    connected_moment,
    expectation_value,
    flavor_correlator_connected,
    flavor_correlator_raw,
    local_charge_product,
    local_flavor_dot_product,
    normalized_charge_correlator,
    raw_moment,
)
from .matching import (
    AMBIGUOUS_CROSS_TRUNCATION_MATCH,
    EXACT_LABEL_MATCH,
    NOT_APPLICABLE,
    NUMERIC,
    STRUCTURALLY_NOT_APPLICABLE,
    TARGET_GROUP_NOT_IN_WINDOW,
    UNAVAILABLE,
    MatchOutcome,
    SpectralGroupMatchKey,
    SymmetryLabel,
    compute_restricted_symmetry_label,
    compute_twice_T,
    match_spectral_group,
    symmetry_labels_match,
)
from .assembly import AssemblyContradiction, AssemblyMetadataMismatch, AssemblyReport, assemble_execution
from .matter import apply_dressed_matter, build_dressed_matter_matrix
from .orbits import (
    DRESSED_MATTER_OBSERVABLE_KIND,
    OrbitComparabilityKey,
    OrbitElement,
    OrbitStatistics,
    ValidatedOrbit,
    aggregate_validated_orbit,
    flavor_component_label,
    validate_orbit_covariance,
)
from .paths import OrientedPath, invert_path, make_oriented_path, minimal_paths
from .restricted import (
    COMPLETE_MULTIPLET,
    PARTIAL_SUBSPACE,
    SpectralGroupState,
    build_restricted_operator,
    canonical_multiplet_expectation,
    exploratory_partial_subspace_mean,
    extract_group_state,
)
from .results import (
    OBSERVABLE_KINDS,
    RECORD_KINDS,
    ROBUSTNESS_OBSERVABLE_KINDS,
    HamiltonianIdentity,
    OrbitResultPayload,
    Provenance,
    ResultRecord,
    ScientificIdentity,
    SpectralGroupIdentity,
    build_orbit_result_payload,
    build_result_record,
)
from .robustness import (
    ABSOLUTE_ROBUSTNESS_THRESHOLD,
    INDETERMINATE,
    NON_ROBUST,
    RELATIVE_ROBUSTNESS_THRESHOLD,
    ROBUST,
    TRUNCATED_SPECTRAL_GROUP,
    RobustnessResult,
    compute_gamma_o,
    evaluate_robustness,
)
from .serialization import SCHEMA_VERSION, serialize_result_record, validate_document
from .transporters import apply_transporter

__all__ = [
    "ABSOLUTE_ROBUSTNESS_THRESHOLD",
    "AMBIGUOUS_CROSS_TRUNCATION_MATCH",
    "AssemblyContradiction",
    "AssemblyMetadataMismatch",
    "AssemblyReport",
    "COMPLETE_MULTIPLET",
    "DRESSED_MATTER_OBSERVABLE_KIND",
    "EXACT_LABEL_MATCH",
    "FLAVOR_COMPONENTS",
    "FlavorCorrelatorMatrix",
    "GraphAutomorphism",
    "HamiltonianIdentity",
    "HermitianRestrictedDiagnostics",
    "INDETERMINATE",
    "MatchOutcome",
    "NON_ROBUST",
    "NORMALIZATION_FLOOR",
    "NOT_APPLICABLE",
    "NUMERIC",
    "NonHermitianRestrictedDiagnostics",
    "NormalizedMoment",
    "OBSERVABLE_KINDS",
    "OrbitComparabilityKey",
    "OrbitElement",
    "OrbitResultPayload",
    "OrbitStatistics",
    "OrientedPath",
    "PARTIAL_SUBSPACE",
    "Provenance",
    "RECORD_KINDS",
    "RELATIVE_ROBUSTNESS_THRESHOLD",
    "ROBUST",
    "ROBUSTNESS_OBSERVABLE_KINDS",
    "ResultRecord",
    "RobustnessResult",
    "SCHEMA_VERSION",
    "STRUCTURALLY_NOT_APPLICABLE",
    "ScientificIdentity",
    "SpectralGroupIdentity",
    "SpectralGroupMatchKey",
    "SpectralGroupState",
    "SymmetryLabel",
    "TARGET_GROUP_NOT_IN_WINDOW",
    "TRUNCATED_SPECTRAL_GROUP",
    "UNAVAILABLE",
    "UnitaryAutomorphism",
    "ValidatedOrbit",
    "aggregate_validated_orbit",
    "apply_dressed_matter",
    "apply_transporter",
    "assemble_execution",
    "build_automorphism",
    "build_dressed_matter_matrix",
    "build_flavor_correlator_matrix",
    "build_hermitian_restricted_diagnostics",
    "build_local_charge_operator",
    "build_local_flavor_generator",
    "build_local_flavor_generators",
    "build_non_hermitian_restricted_diagnostics",
    "build_orbit_result_payload",
    "build_restricted_operator",
    "build_result_record",
    "canonical_multiplet_expectation",
    "charge_correlator_connected",
    "charge_correlator_raw",
    "compose",
    "compose_unitary_automorphisms",
    "compute_gamma_o",
    "compute_restricted_symmetry_label",
    "compute_twice_T",
    "connected_moment",
    "evaluate_robustness",
    "expectation_value",
    "exploratory_partial_subspace_mean",
    "extract_group_state",
    "flavor_component_label",
    "flavor_correlator_connected",
    "flavor_correlator_raw",
    "flavor_frobenius_squared",
    "flavor_singlet",
    "flavor_singular_value_ratio",
    "flavor_singular_values",
    "generate_closed_subgroup",
    "generate_closed_unitary_subgroup",
    "hamiltonian_commutator_defect",
    "identity_automorphism",
    "identity_unitary_automorphism",
    "invert_path",
    "local_charge_product",
    "local_flavor_dot_product",
    "make_oriented_path",
    "match_spectral_group",
    "minimal_paths",
    "normalized_charge_correlator",
    "raw_moment",
    "reflection_automorphism",
    "reflection_unitary_automorphism",
    "serialize_result_record",
    "symmetry_labels_match",
    "symmetry_subgroup",
    "transform_oriented_path",
    "translation_automorphism",
    "translation_unitary_automorphism",
    "validate_document",
    "validate_orbit_covariance",
]
